# Generated by Django 5.2.7 on 2025-11-28 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinacion', '0004_alter_sustentacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientosemanal',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Requiere Correcciones')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='seguimientosemanal',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='seguimientosemanal',
            name='fecha_revision_docente',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='practicaempresarial',
            name='estado',
            field=models.CharField(choices=[('EN_CURSO', 'En Curso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='EN_CURSO', max_length=20),
        ),
        migrations.AlterField(
            model_name='seguimientosemanal',
            name='evidencia',
            field=models.FileField(blank=True, null=True, upload_to='practicas/seguimientos/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png', 'docx', 'zip'])]),
        ),
    ]
