# Generated by Django 5.2.7 on 2025-12-01 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinacion', '0007_coordinador_foto_perfil_docenteasesor_cedula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título de la encuesta', max_length=300)),
                ('descripcion', models.TextField(help_text='Descripción y objetivo de la encuesta')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva'), ('FINALIZADA', 'Finalizada')], default='ACTIVA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateField(help_text='Fecha desde la cual la encuesta está disponible')),
                ('fecha_fin', models.DateField(help_text='Fecha hasta la cual la encuesta está disponible')),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestas_creadas', to='coordinacion.coordinador')),
            ],
            options={
                'verbose_name': 'Encuesta',
                'verbose_name_plural': 'Encuestas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pregunta', models.TextField(help_text='Texto de la pregunta')),
                ('tipo', models.CharField(choices=[('CALIFICACION', 'Calificación 1-5'), ('TEXTO', 'Texto Libre'), ('OPCION_MULTIPLE', 'Opción Múltiple')], default='CALIFICACION', max_length=20)),
                ('orden', models.IntegerField(default=0, help_text='Orden de aparición de la pregunta')),
                ('requerida', models.BooleanField(default=True, help_text='Indica si la pregunta es obligatoria')),
                ('opciones', models.JSONField(blank=True, help_text='Opciones para preguntas de opción múltiple (formato JSON)', null=True)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='coordinacion.encuesta')),
            ],
            options={
                'verbose_name': 'Pregunta de Encuesta',
                'verbose_name_plural': 'Preguntas de Encuesta',
                'ordering': ['encuesta', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('EN_PROGRESO', 'En Progreso'), ('COMPLETADA', 'Completada')], default='EN_PROGRESO', max_length=20)),
                ('calificacion_promedio', models.DecimalField(blank=True, decimal_places=1, help_text='Promedio de calificaciones de la encuesta', max_digits=3, null=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='coordinacion.encuesta')),
                ('practica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestas_respondidas', to='coordinacion.practicaempresarial')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestas_respondidas', to='coordinacion.tutorempresarial')),
            ],
            options={
                'verbose_name': 'Respuesta de Encuesta',
                'verbose_name_plural': 'Respuestas de Encuestas',
                'ordering': ['-fecha_inicio'],
                'unique_together': {('encuesta', 'practica', 'tutor')},
            },
        ),
        migrations.CreateModel(
            name='DetalleRespuestaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(blank=True, help_text='Calificación 1-5 para preguntas tipo calificación', null=True)),
                ('texto_respuesta', models.TextField(blank=True, help_text='Texto para preguntas de texto libre', null=True)),
                ('opcion_seleccionada', models.CharField(blank=True, help_text='Opción seleccionada para preguntas de opción múltiple', max_length=500, null=True)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='coordinacion.preguntaencuesta')),
                ('respuesta_encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='coordinacion.respuestaencuesta')),
            ],
            options={
                'verbose_name': 'Detalle Respuesta Encuesta',
                'verbose_name_plural': 'Detalles Respuestas Encuestas',
                'unique_together': {('respuesta_encuesta', 'pregunta')},
            },
        ),
    ]
