# Generated by Django 5.2.7 on 2025-11-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinacion', '0002_docenteasesor_empresa_estudiante_practicaempresarial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicaempresarial',
            name='estado',
            field=models.CharField(choices=[('EN_CURSO', 'En Curso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='INICIADA', max_length=20),
        ),
    ]
