# Generated by Django 5.2.7 on 2025-11-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinacion', '0003_alter_practicaempresarial_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sustentacion',
            name='estado',
            field=models.CharField(choices=[('PROGRAMADA', 'Programada'), ('APROBADA', 'Aprobada'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', max_length=20),
        ),
    ]
