# Generated by Django 5.2.7 on 2025-11-30 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinacion', '0005_seguimientosemanal_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientosemanal',
            name='calificacion',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Calificación del docente asesor (0.0 - 5.0)', max_digits=3, null=True),
        ),
    ]
