# Generated by Django 5.2.7 on 2025-11-30 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinacion', '0006_seguimientosemanal_calificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinador',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Foto de perfil del coordinador', null=True, upload_to='coordinadores/fotos_perfil/'),
        ),
        migrations.AddField(
            model_name='docenteasesor',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='docenteasesor',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Foto de perfil del docente asesor', null=True, upload_to='docentes/fotos_perfil/'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Foto de perfil del estudiante', null=True, upload_to='estudiantes/fotos_perfil/'),
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(help_text='Contenido del mensaje')),
                ('archivo_adjunto', models.FileField(blank=True, help_text='Archivo adjunto opcional', null=True, upload_to='mensajes/adjuntos/')),
                ('leido', models.BooleanField(default=False, help_text='Indica si el mensaje fue leído')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('practica', models.ForeignKey(help_text='Práctica a la que pertenece el mensaje', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='coordinacion.practicaempresarial')),
                ('remitente', models.ForeignKey(help_text='Usuario que envía el mensaje', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['fecha_envio'],
            },
        ),
    ]
