# Generated by Django 5.2.7 on 2025-12-01 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinacion', '0008_encuesta_preguntaencuesta_respuestaencuesta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorempresarial',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Foto de perfil del tutor empresarial', null=True, upload_to='tutores/fotos_perfil/'),
        ),
        migrations.AddField(
            model_name='tutorempresarial',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Usuario asociado al tutor empresarial', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_empresarial', to=settings.AUTH_USER_MODEL),
        ),
    ]
